import type {Config} from 'tailwindcss'
import typography from '@tailwindcss/typography'

export default {
  content: ['./app/**/*.{ts,tsx}', './sanity/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    container: {
      center: true,
      padding: '2rem',
    },
    extend: {
      boxShadow: {
        layer: '0 35px 60px -15px rgba(0, 0, 0, 0.3)',
      },
      colors: {
        black: '#0d0e12',
        white: '#fff',
        'outline-variant': 'var(--color-outline-variant)',
        'on-primary-fixed-variant': '#544243',
        'secondary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed-variant': '#474646',
        surface: 'var(--color-surface)',
        'surface-container': 'var(--color-surface-container)',
        'error-container': '#ffdad6',
        'on-secondary-container': '#5f6161',
        'on-primary-container': '#725e5e',
        'on-tertiary-container': '#636262',
        'primary-fixed-dim': '#dac1c1',
        'on-secondary-fixed-variant': '#454747',
        'secondary-container': '#dcdddd',
        'secondary-fixed': '#e2e2e2',
        'on-secondary': '#ffffff',
        'inverse-primary': '#dac1c1',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        background: 'var(--color-background)',
        'on-error': '#ffffff',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-variant': 'var(--color-surface-variant)',
        'inverse-surface': '#2f3131',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': '#4e4444',
        'on-secondary-fixed': '#1a1c1c',
        'on-primary-fixed': '#261818',
        'inverse-on-surface': '#f0f1f1',
        'primary-container': '#f4dada',
        'on-primary': '#ffffff',
        'tertiary-container': '#e2dfde',
        'surface-container-high': '#e8e8e8',
        primary: 'var(--color-primary)',
        outline: '#807474',
        'tertiary-fixed': '#e5e2e1',
        'surface-container-low': '#f3f3f4',
        secondary: '#5d5f5f',
        'surface-bright': '#f9f9f9',
        'on-tertiary-fixed': '#1c1b1b',
        'surface-tint': '#6d5a5a',
        'primary-fixed': '#f7dcdc',
        'surface-dim': '#dadada',
        'on-background': 'var(--color-on-background)',
        error: '#ba1a1a',
        tertiary: '#5f5e5e',
        cyan: {
          50: '#e7fefe',
          100: '#c5fcfc',
          200: '#96f8f8',
          300: '#62efef',
          400: '#18e2e2',
          500: '#04b8be',
          600: '#037782',
          700: '#024950',
          800: '#042f34',
          900: '#072227',
          950: '#0d181c',
        },
        gray: {
          50: '#f6f6f8',
          100: '#eeeef1',
          200: '#e3e4e8',
          300: '#bbbdc9',
          400: '#9499ad',
          500: '#727892',
          600: '#515870',
          700: '#383d51',
          800: '#252837',
          900: '#1b1d27',
          950: '#13141b',
        },
        red: {
          50: '#fff6f5',
          100: '#ffe7e5',
          200: '#ffdedc',
          300: '#fdada5',
          400: '#f77769',
          500: '#ef4434',
          600: '#cc2819',
          700: '#8b2018',
          800: '#4d1714',
          900: '#321615',
          950: '#1e1011',
        },
        orange: {
          50: '#fcf1e8',
          100: '#f9e3d2',
          200: '#f4c7a6',
          300: '#efab7a',
          400: '#ea8f4e',
          500: '#e57322',
          600: '#ba5f1e',
          700: '#8f4b1b',
          800: '#653818',
          900: '#3a2415',
          950: '#251a13',
        },
        yellow: {
          50: '#fefae1',
          100: '#fcf3bb',
          200: '#f9e994',
          300: '#f7d455',
          400: '#f9bc15',
          500: '#d28a04',
          600: '#965908',
          700: '#653a0b',
          800: '#3b220c',
          900: '#271a11',
          950: '#181410',
        },
        green: {
          50: '#e7f9ed',
          100: '#d0f4dc',
          200: '#a1eaba',
          300: '#72e097',
          400: '#43d675',
          500: '#3ab564',
          600: '#329454',
          700: '#297343',
          800: '#215233',
          900: '#183122',
          950: '#14211a',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1280px',
        lg: '48px',
        xl: '80px',
        'margin-mobile': '20px',
        md: '24px',
        base: '8px',
        sm: '12px',
        gutter: '24px',
        xs: '4px',
      },
      fontFamily: {
        sans: ['var(--font-manrope)', 'sans-serif'],
        mono: ['var(--font-ibm-plex-mono)'],
        'label-sm': ['var(--font-manrope)'],
        'headline-md': ['var(--font-playfair-display)'],
        'display-lg': ['var(--font-playfair-display)'],
        'headline-lg': ['var(--font-playfair-display)'],
        'body-lg': ['var(--font-manrope)'],
        'body-md': ['var(--font-manrope)'],
        'label-lg': ['var(--font-manrope)'],
        'display-lg-mobile': ['var(--font-playfair-display)'],
        'headline-lg-mobile': ['var(--font-playfair-display)'],
      },
      fontSize: {
        'label-sm': [
          '12px',
          {
            lineHeight: '1.2',
            letterSpacing: '0.03em',
            fontWeight: '500',
          },
        ],
        'headline-md': [
          '24px',
          {
            lineHeight: '1.3',
            fontWeight: '500',
          },
        ],
        'display-lg': [
          '72px',
          {
            lineHeight: '1.1',
            letterSpacing: '-0.02em',
            fontWeight: '700',
          },
        ],
        'headline-lg': [
          '40px',
          {
            lineHeight: '1.2',
            fontWeight: '600',
          },
        ],
        'body-lg': [
          '18px',
          {
            lineHeight: '1.6',
            fontWeight: '400',
          },
        ],
        'body-md': [
          '16px',
          {
            lineHeight: '1.6',
            fontWeight: '400',
          },
        ],
        'label-lg': [
          '14px',
          {
            lineHeight: '1.2',
            letterSpacing: '0.05em',
            fontWeight: '600',
          },
        ],
        'display-lg-mobile': [
          '48px',
          {
            lineHeight: '1.1',
            letterSpacing: '-0.01em',
            fontWeight: '700',
          },
        ],
        'headline-lg-mobile': [
          '32px',
          {
            lineHeight: '1.2',
            fontWeight: '600',
          },
        ],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [typography],
} satisfies Config
